version: '3'

volumes:
  data:

services:
  saml:
    image: lib-simplesamlphp/simplesamlphp:latest
    environment:
      - SIMPLESAML_DIR=/var/simplesamlphp
    volumes:
      - data:/var/simplesamlphp
    ports:
      - 8080
    restart: always
